name: opensoul.org
url: http://opensoul.org
markdown: redcarpet
highlighter: true
copyright: 2006
permalink: /:year/:month/:day/:title/
assets:
  cache: true
exclude:
- script
- Gemfile
- Gemfile.lock
- scratch.md
destination: _site/local
