name: opensoul.org
url: http://opensoul.org
markdown: redcarpet
pygments: true
copyright: 2006 - 2013
permalink: /:year/:month/:day/:title/
assets:
  cache: true
exclude:
- script
- Gemfile
- Gemfile.lock
- scratch.md
destination: _site/local
