name: opensoul.org
url: http://opensoul.org
markdown: redcarpet
copyright: 2006
permalink: /:year/:month/:day/:title/
assets:
  cache: true
exclude:
- script
- Gemfile
- Gemfile.lock
- scratch.md
- vendor
gems:
- jekyll-redirect-from
- jekyll-sitemap
