name: opensoul.org
url: http://opensoul.org
markdown: redcarpet
copyright: 2006
permalink: pretty
assets:
  cache: true
exclude:
- script
- Gemfile
- Gemfile.lock
- scratch.md
- vendor
- test
- Rakefile
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
author:
  name: Brandon Keepers
  email: brandon@opensoul.org
  uri: http://opensoul.org
  twitter: bkeepers
amazon_associate_id: opensoulorg0d-20
branch: master
repository: bkeepers/bkeepers.github.io

# SEO
google_site_verification: h4QNmQOrsvnIEsMH5GS3s4_jV3ZAZgrEoZdL4RsbOMI
title: Brandon Keepers
description: Open source advocate, speaker, developer

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
