name: opensoul.org
url: http://opensoul.org
markdown: redcarpet
copyright: 2006
permalink: /:year/:month/:day/:title/
assets:
  cache: true
exclude:
- script
- Gemfile
- Gemfile.lock
- scratch.md
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
author:
  name: Brandon Keepers
  email: brandon@opensoul.org
  uri: http://opensoul.org
amazon_associate_id: opensoulorg0d-20
