#!/usr/bin/env ruby

require 'bundler/setup'
require 'html-proofer'

# Ignore really old content for now
ignores = %w(
  _site/blog/**/*.html
  _site/20{05,06,07,08,09,10}/**/*.html
  _site/assets/*.html
).map {|p| Dir.glob(p) }.flatten

HTMLProofer::Runner.new(['_site'],
  :type => :directory,
  :file_ignore => ignores,
  :verbose => !!ENV["VERBOSE"],
  :check_html => true,
  :url_swap => {%r{^http://opensoul.org} => ""}
).run
