#!/usr/bin/ruby

Dir['_posts/*/*.textile'].each do |file|
  content = File.read(file)

  content.scan(/\!([^\s]+)(?: \((.*)\))?\!/).each do |link, alt|
    filename = File.basename(link)

    # url = link
    # url = "http://opensoul.org#{link}" unless link =~ /^http/

    # url.gsub!('halfcontent', 'original')
    # url.gsub!('content', 'original')
    # url.gsub!('medium', 'original')

    # Dir.chdir('_assets/images') do
    #   `wget #{url}` unless File.exists?(filename)
    # end

    img_tag = if File.exists?("_assets/images/#{filename}")
      "{% image #{filename} %}"
    else
      "<!-- Image not found: #{link} -->"
    end

    content.gsub! /\!#{link}[^\!]*\!/, img_tag
  end

  File.open(file, 'w') { |f| f << content }
end
